<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath>C:\pikkatech.eu\Projects\Agadir\Code\CSharp\Binary</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Factotum\Code\CSharp\Factotum.csproj" />
    <ProjectReference Include="..\Agadir.Library\Agadir.Library.csproj" />
  </ItemGroup>

</Project>